### ISSUE TITLE
imageResizable style dimensions stripped on subsequent save

### ISSUE THREAD

**Issue by lukasgeiter** [craftcms/redactor#192]
When using a redactor field with `imageResizable` enabled, resizing the image and then saving adds a  `style` attribute to the `<img>` element which declares width and height of the image:

```html
<img src="..." width="555" height="370" style="width: 555px; height: 370px;">
```

However whenever I save the entry without resizing the image, the `style` attribute is removed.

```html
<img src="..." width="555" height="370">
```

I would expect the `style` attribute to remain the same when saving multiple times without making any changes. As a workaround, authors always have to remember to resize images slightly before saving to retain the attribute, which is far from ideal.

#### Steps to reproduce:

1. Create entry with redactor field
1. Add image to redactor field
1. Resize the image
1. Save > `style` attribute is set
1. Save again (without resizing) > `style` attribute is removed

#### Versions:

Craft: 3.3.18.4
Redactor Plugin: 2.4.0

**Comment by chasegiunta** [comment]
@lukasgeiter you may want to ensure you don't have the "Remove inline styles" option checked in the advanced section of the field's settings.

![image](https://user-images.githubusercontent.com/1377169/73866147-f75a0980-4809-11ea-9819-535e07918c24.png)

**Comment by andris-sevcenko** [comment]
I took a rather deep dive through Redactor's code. It appears that Redactor sanitizes the field value on load, which also includes removing the `style` attribute on all image tags. ([source](https://github.com/craftcms/redactor/blob/d343eba0e3203c88f051055b8a59e9914c50d4ad/lib/redactor/redactor.js#L5641-L5651))

So, I went ahead and overrode that behavior, allowing the `style` attribute to stay on the `img` tags, since it's possible to remove them on save with field settings

**Comment by andris-sevcenko** [comment]
This will be included in the next release!

**Comment by lukasgeiter** [comment]
@andris-sevcenko Thanks!
