### ISSUE TITLE
Redactor plugins in Redactor plugin settings

### ISSUE THREAD

**Issue by tu5** [craftcms/redactor#2]
It would be great to have all plugins in Redactor settings, with possibility to modify their settings like in clips.js :-)

**Comment by brandonkelly** [comment]
I’m not entirely sure I’m following you. Are you saying Redactor should ship with all of the official [Redactor plugins](https://imperavi.com/redactor/plugins), and the field settings should have UIs for enabling which ones you want (and any settings associated with them)? If so that’s definitely out of scope for the plugin.

**Comment by brandonkelly** [comment]
Closing due to lack of response.
