### ISSUE TITLE
Redactor fields in secondary tabs not initialising

### ISSUE THREAD

**Issue by domstubbs** [craftcms/redactor#21]
Craft only seems to initialise Redactor fields on the active tab when the page loads. Navigating to a different tab containing a Redactor field just reveals a generic `<textarea>`.

[This comment](https://github.com/craftcms/cms/issues/2699#issuecomment-379307709) looks like it might be related.

Tested with Craft 3.0.1, Redactor 1.1.0 in Safari and Chrome.

**Comment by LauraMontgomery** [comment]
I am having a similar issue to this also. I have a Redactor field within a Matrix block. The Matrix blocks that are visible/active on page load are fine - the Redactor toolbar initialises. However, if I add a new block to the Matrix, the Redactor toolbar fails to initialise, leaving what looks like a regular textarea. Saving and reloading the page then enables the toolbar on the new block.

Adding my comment here because it sounds like it could be related to issue above.

**Comment by evanwarner** [comment]
Same issue as @domstubbs. If I refresh the page while on a sub-tab, the toolbar initializes correctly.

**Comment by jllavoie** [comment]
Yeah I'm having the same issue too.

When refreshing the page while on a tab, the toolbar initializes properly, but all other Redactor fields under other tabs lose their full UI (they become just textareas.)

Tested with Craft 3.0.4, Redactor 1.1.0 in Chrome.

**Comment by andris-sevcenko** [comment]
Fixed with the 2.0 release of the plugin.
