### ISSUE TITLE
Responsive + lazyloaded images

### ISSUE THREAD

**Issue by nicbou** [craftcms/redactor#220]
It would be great to be able to somehow add the "lazyload" attribute to images. I have a page that has 15 MB worth of large images, and they should not be loaded all at once.

It would also be great to make use of the srcset and sizes attributes, somehow. The mobile version of my page doesn't need desktop-sized high DPI images.

**Comment by olivierbon** [comment]
@nicbou Not truly an answer on the Redactor side of things but you should be able to do what you want using the [Retcon plugin](https://plugins.craftcms.com/retcon) for now. [Here's the documentation](https://github.com/mmikkel/Retcon-Craft/wiki/srcset) on the `srcset` attribute and they also touch on lazy loading.

**Comment by nicbou** [comment]
Yes, that might have to do it for now. I already have a small plugin that creates a table of contents, so I could always adapt it.

Thanks for the tip. If you don't mind, I'd like to leave that issue open.

**Comment by andris-sevcenko** [comment]
This will usually be more site-specific. The `srcset` breakpoints will usually vary from site to site and the exact implementation of what lazyloading scheme and attribute to use can also differ between sites.

For this reason, it's better to manage this via Retcon, for example.

**Comment by nicbou** [comment]
Couldn't this be configured? RetCon is quite literally a patch, not a proper solution

**Comment by andris-sevcenko** [comment]
I'm not quite sure I'd call "using a plugin for it's intended purpose" a patch.

The responsibility of determining the appropriate size/transform per breakpoint should be up to the developer of the page, not the content editor. More often than not, a content editor will have limited awareness of what breakpoints should be taken into account and which transform is correlated to that.

In a similar fashion, wouldn't you want to lazy-load all of the images for a given Redactor field?Also, there is no uniform support in browsers for this, which means that it wouldn't be a checkbox, but rather a textbox where you type in the attribute you want to add so that your javascript libs can then add lazy-loading support. Which, again, means that the content editor should be aware of a site's implementation details, which is not ideal.
