### ISSUE TITLE
edit HTML button off by default for non-admin users when it was previously enabled

### ISSUE THREAD

**Issue by dlindberg** [craftcms/redactor#257]
### Description

The resolution to #129 creates a somewhat annoying update issue that wasn't really clear form the change log. When updating the `Show the “HTML” button for non-admin users` defaults to `false` for all existing redactor fields, which means they all need to be updated so that non-admin users can get to them where they previously had been enabled. While requiring an explicit setting of allow to edit seems right for new fields, it is something of a nuisance for existing fields that, in this case, I didn't catch until users started complaining that they needed to make an HTML edit *now*.

Tying this into the permissions system seems like it could be a granular way to solve the issue. Eg adding a Redactor permission of `can edit HTML` that you could assign to some but not all user groups. That way if you have users you want to allow to edit HTML you can grant it without giving full admin access and without granting HTML editing to everyone if some users need to be restricted from that ability. The per field allow could still be useful in that scenario (as either an override of let everyone or "no really only admins can edit HTML here", but this seems more logical as a user permission than a field permission, at least to me.

**Comment by andris-sevcenko** [comment]
Going forward, this setting for existing fields will default to true.

It's not a great fit for permissions, because all it does is obscure HTML editing away and is not really a _permission_.

A better way to do that would probably be via a custom module (https://github.com/craftcms/redactor/issues/226)

**Comment by geenious** [comment]
Where can you update this permission for non-admin users?

**Comment by DynamiteGoesBoom** [comment]
i see that @andris-sevcenko changed the default for the `Show the “HTML” button for non-admin users` behavior but I was curious if there were any plans to add the ability for user groups based ability to `Edit HTML` as @dlindberg originally mentioned?

**Comment by andris-sevcenko** [comment]
@DynamiteGoesBoom not really. It is not a permission, because all it does is make editing HTML less easy, so what you're looking for is a "user group-based field settings", which is better solved by a custom module and events (possible as of https://github.com/craftcms/redactor/commit/337a7420fd79e94d585d09d9a74b81ef1f312b3f).

Incidentally, the [example](https://github.com/craftcms/redactor/blob/v2/src/Field.php#L79-L95) for using the event is very close to what you need.

**Comment by DynamiteGoesBoom** [comment]
@andris-sevcenko Thanks for the info but I think that seems like a bit overkill for our needs. It would be nice if there was just some sort of value we could pass into one of the `config/redactor` `.json` files versus needing to write a module for it.

We may just enable that setting but that's also kind of annoying as we'll need to manually check all of those boxes throughout this rather large application.

But I do appreciate the response and all that you lovely folks do to make our lives easier!

**Comment by andris-sevcenko** [comment]
I certainly agree that it's cumbersome, but, on the other hand, adding support for different field settings per user group is something that should probably be handled on the Craft level, not the plugin level.

**Comment by andris-sevcenko** [comment]
Also, thank you for the kind words :)
