### ISSUE TITLE
Craft 3 App Install Breaks Site

### ISSUE THREAD

**Issue by mike-rotate** [craftcms/redactor#26]
While installing Redactor through the Craft 3 app store CP page, the installation failed and left me with a broken site.

I worked out that in my `craft_info` table in the DB, the `version` and `schemaVersion` had become out of sync somewhere during the failed install.

changing `schemaVersion` to `3.0.3.1`  to match `version`, i then refreshed the admin CP page, `Craft` told me there were some DB changes to apply, i click continue, once complete, the site was back up and running again and Redactor was installed.

**Comment by andris-sevcenko** [comment]
@angrybrad  seems like this would belong over at `craftcms/cms` rather than here?

**Comment by brandonkelly** [comment]
@mike-rotate Is your site under version control? Do you happen to know what changes were made to your composer.json and composer.lock files during this install?

It sounds like Craft was updated in the process of installing Redactor, which should not have happened. The only way I can think of where that may have happened is if your composr.json file specified a higher version of Craft than you actually had installed – perhaps because a colleague updated Craft and you hadn’t run `composer install` locally yet.

**Comment by mike-rotate** [comment]
@brandonkelly indeed we were updating craft too. We had clicked the `update all` under `/admin/utilities/updates`. I'm afraid at this point however we hadn't version controlled the site so we don't have the difference in composer.json file. Perhaps during the `update all`, there was maybe a mishap in the order of updating craft & plugins?
