### ISSUE TITLE
Required fields aren’t validated

### ISSUE THREAD

**Issue by rlapierre-kffein** [craftcms/redactor#260]
#### Description
Redactor fields that are required doesn't pass validation as entry can be saved without any errors. Others fields like image show validation errors when required.

I submitted issue first on craft neo plugin as I thought issue came from Neo plugin but another user has been able to reproduce this bug directly on an entry (https://github.com/spicywebau/craft-neo/issues/394)

#### Steps to reproduce (first case)
1. Insert a redactor field into a section
2. Mark as required
3. Try to save the entry with empty data on redactor field.
4. Validation should not throw any errors but let user save entry.

#### Steps to reproduce (second case)
1. Insert two redactor field into a section
2. Mark them as required.
3. Insert text into it and save it.
4. Remove text from input and try to save it. Validation pass even if it's required.
5. Save it again and validation will throw error as it's required.

#### Capture

![Alt Text](https://s7.gifyu.com/images/ezgif-4-3ffab93a90b3.gif)

#### Other information
- Craft version: 3.5.5

**Comment by brandonkelly** [comment]
I’m unable to reproduce this, either within a normal Redactor field, or one within a Matrix block type.

Can you try adding the `html` button to your redactor config, and see if there’s any unexpected HTML in there?

**Comment by ttempleton** [comment]
Here's what I found, using the Happy Lager demo, Craft 3.5.10.1, Redactor plugin 2.7.4.

I set the Body field as required on the About section, then I blanked the Body field on the entry and was able to save without errors.  After adding the HTML button, after blanking the field and viewing the HTML the first time, it contains `<p><br></p>`.  After returning to the normal display and trying to save, it then fails validation.  If I view the HTML a second time, rather than try to save, there is no HTML.

Let me know if there's any other info I should provide.

Tested with Chrome 85.0.4183.102, Firefox 80.0.1, Safari 14.0
PHP version: 7.3.11
MySQL version: 8.0.18

**Comment by andris-sevcenko** [comment]
@ttempleton sorry for the delay - I was able to fix this for the next release. The problem was that Redactor field was normalizing `<p><br></p>` to null only when serializing to database, when validation had already happened. I moved it to the normalizing stage, instead.

**Comment by brandonkelly** [comment]
Redactor 2.9.0 is out now with this fix.
