### ISSUE TITLE
Add option for automatically wrapping outputted redactor content with HTML element

### ISSUE THREAD

**Issue by piotrpog** [craftcms/redactor#310]
Use case - automatically applying some CSS class to redactor content that is used to style rich text, by for example adding specific line height or padding below paragraphs.

**Comment by andris-sevcenko** [comment]
I might be missing something, but this sounds like something you would do in the templates?

**Comment by MisterMike** [comment]
Sorry for taking on this older issue. 

Unless your issue is not related to what Andris replied to, you can do something like this if you wish to add a custom class to the default paragraph element:

`{{ block.richtext | replace({'<p>': '<p class="redactor">'}) | raw }}`

Then you can style your redactor content using that class.

Basically I tend to try to have the p element styled in general – in the context that `<p>` already _is_  a paragraph and thus only appears in redactor fields :-)

**Comment by andris-sevcenko** [comment]
I'll go ahead and close this as you can either use the solution by @MisterMike or take care of this in templates.
