### ISSUE TITLE
The background-colour from the Fontcolor plugin is removed

### ISSUE THREAD

**Issue by alexsanderson** [craftcms/redactor#315]
The [Fontcolor](https://imperavi.com/redactor/plugins/fontcolor/) plugin sets two CSS properties: `color` and `background-color`. The line below allows the `color` through, but not the `background-colour`, removing the chosen highlight.

https://github.com/craftcms/redactor/blob/dd70560df56ec7aef87fe52115fa571d13468714/src/Field.php#L1051-L1053

**Comment by mtnorthrop** [comment]
I've also run into this issue. Unfortunately, the only way to enable highlight colors in Redactor's Fontcolor plugin is by unchecking the "Remove inline styles" checkbox when configuring your Redactor field in the control panel, which I would rather not do because it seems to me that removing most inline styles is helpful, especially when users try to copy/paste rich text.

**Comment by andris-sevcenko** [comment]
Nice catch! Fixed this for the next release!

**Comment by brandonkelly** [comment]
Redactor 2.9.0 is out now with this fix.
