### ISSUE TITLE
Inserting entry link in other site suggests wrong site

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/redactor#372]
### Description
We have a multi domain setup, site-x.nl and site-y.nl, so separate site groups. The control panel works on site-x.
When inserting a link we get the wrong site suggested

### Steps to reproduce

1. Go to site-y to edit an entry
2. Add an link to an entry
3. You get site-x suggested to select from instead of the site you are editing, site-y

### Additional info

- Craft version: 3.7.34
- PHP version: 8.0.x
- Database driver & version: MySQL 8.0
- Plugins & versions: Redactor 2.9+, ...

**Comment by andris-sevcenko** [comment]
Is the link to the correct site, though (the `@<id>` part of the element reference) ? I'm not writing this off, just trying to figure if the wrong like is passed from the entry selection modal or the wrong site is selected in the dropdown, while retaining the correct link.

**Comment by texasbaptists** [comment]
This is also affecting us. We have an 11-site installation. 

When we try to link and select entries in a redactor field it defaults to one specific site instead of the site we are editing. The site that it tries to link to is not the primary site, it is the last site site alphabetically in the last site group alphabetically. We are able to choose the right site, and find the right entry, but it's creating additional clicks to get to what seems should be default... that you are mainly trying to link to entries in the same site. 

Hope this helps.

**Comment by andris-sevcenko** [comment]
We found the guy who's responsible for it and he is very sorry. (It was me)

Fixed this and cut a 2.10.5 release with the fix!

**Comment by umkasanki** [comment]
Hey @andris-sevcenko 
I updated the plugin and cms.
Cleared the CMS and browser cache.
The problem still exists.
Could you check it?

https://user-images.githubusercontent.com/496132/157830940-1f24327c-8b5e-48ee-91c2-6fe266441adf.mp4

**Comment by brandonkelly** [comment]
Redactor 2.10.9 and 3.0.1 are out with a (working) fix for this (c5f1466606a53fd50f94d9af43dfa3db5a5563a9).
