### ISSUE TITLE
Unlinking a link and then inserting it again removes other links

### ISSUE THREAD

**Issue by ai5679** [craftcms/redactor#384]
### Description
Unlinking a link and then inserting it again removes other links in a paragraph. 

### Steps to reproduce

1. Unlink a link
2. Insert the link again
3. The link earlier in the text disappears.

**Screen recording** of the issue: https://jmp.sh/9jOwd97

![image](https://user-images.githubusercontent.com/102757620/161156199-b02ed7d6-abde-4aa3-bf5a-f4b6d36c1cc6.png)

![image](https://user-images.githubusercontent.com/102757620/161156241-98ce74ed-30f6-4436-a880-58be495e7668.png)

### Additional info

- Redactor version: 2.10.3

**Comment by umkasanki** [comment]
We have same issue

**Comment by corneliusio** [comment]
Our team has also been experiencing this on a client site, but even without having first unlinking a link. From what I can tell these are the specific factors that seem to be at play.

1. Only seems to occur when linking an entry, asset, or category. Inserting a custom URL does not appear to be causing this. 
2. If the text being link proceeds all other links in the field, the link is inserted as expected.
3. If the first item is true and the text being linked follows any other links, the immediately preceding link is overwritten with both the URL and text being defined for the new link, leaving the original text intended to be linked unchanged.

There seems to be something occurring with the loss of focus on the input field when the Craft CMS modal for selecting entries opens, when the input is refocused after an entry is selected, the selection area of the text appears to jump to the preceding link and overwrite it instead of inserting the new anchor tag.

For us, this is occurring on Craft@3.7.36 and Redactor@2.10.5 and the installation is using multi-site, on the off chance that's important.

**Comment by ahockemeyer** [comment]
We also are running into this on multiple sites. Ran all the updates and still having this issue. Please prioritize this, our clients need to edit content.

**Comment by bengreenbank** [comment]
We are experiencing the same issue on multiple sites.

**Comment by sparkison** [comment]
Have the *exact* same issues as @corneliusio using Craft 3.7.20 and Redactor 2.7.5 - 2.10.6

**Comment by smockensturm** [comment]
Same here. What's going on @brandonkelly ?

**Comment by stefanfriedrich** [comment]
same issue for us. clients can't edit the content correctly anymore. @brandonkelly

**Comment by timkelty** [comment]
Could you please test this out and confirm it is working:

```
"craftcms/redactor": "dev-fix-link-replacement",
```

**Comment by brandonkelly** [comment]
@stefanfriedrich Thanks for testing! Just tagged 2.10.7 and 3.0.0-beta.3 with the fix.

**Comment by sparkison** [comment]
We're still experiencing this issue with Craft 3.7.27.2 and Redactor 2.10.7. Specifically the issues/steps outlined by @corneliusio above:

> 1. Only seems to occur when linking an entry, asset, or category. Inserting a custom URL does not appear to be causing this.
> 2. If the text being link proceeds all other links in the field, the link is inserted as expected.
> 3. If the first item is true and the text being linked follows any other links, the immediately preceding link is overwritten with both the URL and text being defined for the new link, leaving the original text intended to be linked unchanged.

**Comment by stefanfriedrich** [comment]
works with normal links, but still causes problems with links zu assets.

**Comment by timkelty** [comment]
@stefanfriedrich @sparkison I can no longer reproduce this with Redactor 2.10.7 (with links to entries or assets):

Here is a video: https://user-images.githubusercontent.com/18329/166471307-93193e01-f38c-4229-9158-80882644919f.mp4

Can you ensure your browser caches are cleared and also clear control panel resource caches?
<img width="266" alt="CleanShot 2022-05-03 at 10 21 27@2x" src="https://user-images.githubusercontent.com/18329/166471522-d5551ca2-7a3a-41ae-9562-3d4d1eb53aaa.png">
