### ISSUE TITLE
imageResizable Broken

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/redactor#39]
As of the Redactor 3 upgrade, the [imageResizable](https://imperavi.com/redactor/docs/settings/image/#s-imageresizable) setting is broken. 

Used to be able to grab the handle and resize the image.

**Comment by brandonkelly** [comment]
@andris-sevcenko This is working on https://imperavi.com/redactor – 

1. go to the page and run this JS in your console:

    ```javascript
    selectorOpts.air.imageResizable = true;
    ```

2. click on “Air Toolbar”

So must be a bug with our implementation.

I just updated to Redactor 3.0.8 as there have been a couple image-related changes since 3.0.6, but this is still not working for me.

**Comment by andris-sevcenko** [comment]
Fixed in 87bbb39
