### ISSUE TITLE
Craft.js object breaks when opening redactor field in element HUD

### ISSUE THREAD

**Issue by Anubarak** [craftcms/redactor#64]
I receive an `Uncaught TypeError: Craft.appendFootHtml is not a function` when the redactor plugin is installed in my system and I try to open an element HUD. 

I can disable all other plugins and use a new Craft 3 installation, clear all caches (Craft cache as well as my browser cache) and the error still occurs. I wasn't able to track the reason.

Just an additional note: I needed to modify a few lines in `RedactorInput.js` since they throw errors

```
if (typeof this.redactorConfig.buttons !== 'undefined' && this.redactorConfig.buttons.indexOf('image') !== -1) {
```
`this.redactorConfig.buttons` is always undefined when I install the plugin, so I checked for the type

Craft CMS version: Craft Pro 3.0.13.2
Redactor Version: v2.x-dev

**Comment by Naffto** [comment]
The reason, the HUD is breaking while opening the element editor in a modal is because the FieldAsset is dependent on the CpAsset.

Because of this dependency, the Craft object gets returned in the admin/actions/elements/get-editor-html ajax response. Specifically in the "headHtml" part of the response.
And when the headHtml part gets appended to the DOM, the existing, fully initialised, Craft object is overriden.
Now the next call to appendFootHtml will throw the error.
