### ISSUE TITLE
links in lists

### ISSUE THREAD

**Issue by cstudios-slovakia** [craftcms/redactor#69]
this is how you reproduce the error. Hopefully, it is not installation specific:

1. create a list of items
2. add a link to the third item
3. save
4. then add a link to the first element
5. save
6. now to the second
7. save

after saving the list has the same URL on all of its element, even it should be different. The HTML structure is fine.

**Comment by andris-sevcenko** [comment]
It's a Redactor bug and I've reported this to Imperavi already. Hopefully, they fix it soon.

**Comment by andris-sevcenko** [comment]
Still unfixed as of Redactor 3.1.1

**Comment by andris-sevcenko** [comment]
Still unfixed as of Redactor 3.1.2

**Comment by ben-rogerson** [comment]
The latest version of Redactor has some references to a bug with links in lists. Do you know if this addresses the bug? https://imperavi.com/redactor/log/

**Comment by andris-sevcenko** [comment]
Seems to be resolved with the latest Redactor version. Working my way down the priority list to get to a new Redactor plugin release.

**Comment by sjcallender** [comment]
We're still on Redactor 2.1.7 because we can't upgrade to Craft 3.1.x yet.

On Redactor 2.1.7, this is still an issue. Do you know, for sure, if this is fixed in the newer versions?

![screen recording 2019-02-06 at 01 04 pm](https://user-images.githubusercontent.com/984311/52363258-4eb77500-2a10-11e9-8697-ede856b30c5f.gif)
