### ISSUE TITLE
Prevent anchor tag in File links?

### ISSUE THREAD

**Issue by tmulry** [craftcms/redactor#71]
Craft version: 3.0.16
Redactor Plugin version: 1.1.0 (using Redactor JS 2.x)

1. Go to a rich text field with a file button.
2. choose an asset (like a pdf) to link to. Ours are on S3 in this case.
3. A link to the file appears in the field. The link appears with a url, something like:
https://s3-us-gov-west-1.amazonaws.com/some.bucket/Folder-1/Folder2/Mundane-Doc-Title.pdf#asset:123456:url
4. After the link appears, mouse over it and click Edit Link.  
5. Change the label and click Save.

Expected behavior:
Save processes immediately

Actual:
The save takes nearly 20 Seconds to process. Here is the chrome profiler for clicking that save button.  Note that 17.7s spent on a single regex:

![image](https://user-images.githubusercontent.com/4219434/43006136-8cf6a3cc-8bfa-11e8-8868-301433849d88.png)

However, If I go in and drop the anchor tag from the url, I can save the link immediately.  Moreover, if I keep the anchor and just remove the colons, the save also processes immediately.  

While I realize the Regex in Redactor.js is ultimately to blame here, would it be possible to remove the autogenerated anchor tag from the file link altogether?

**Comment by andris-sevcenko** [comment]
The anchor is required for Craft to know which Asset was linked. The URL is actually stored in the DB on the field save as {asset:123456:url}, so that, if the Asset is moved or it's URL changes, all the URLs in the content are updated automatically.

Have you considered updating to the latest Redactor Plugin version? The development of v1 branch has halted, anyway and I'm pretty sure that Redactor Plugin v1 will not be compatible with Craft 3.1 when it comes out.
