### ISSUE TITLE
figcaption - image alignment issue

### ISSUE THREAD

**Issue by karan-saluja** [craftcms/redactor#84]
the figcaption does not align center, even when its parent image is aligned center.
I think you need to remove this style
  .redactor-styles figcaption {
    
    text-align: left; //==>this one 
}

**Comment by andris-sevcenko** [comment]
How are you aligning the image?

**Comment by karan-saluja** [comment]
I added 
"imagePosition": true,
in my config. 

Then I edit my image. And change the "Position" dropdown
![download](https://user-images.githubusercontent.com/28668444/47648586-73de5100-dba0-11e8-9d44-0f5e4530bd86.png)

**Comment by andris-sevcenko** [comment]
This behaves exactly the same as the image aligning on https://imperavi.com/redactor/examples/images-and-files/image-resizing-and-positioning/, tagging as a redactor bug.

**Comment by andris-sevcenko** [comment]
This was fixed in Redactor version 3.1.5, which was part of the 2.3.0 release of this plugin.

**Comment by alanheppenstall** [comment]
Seems to still be an issue in 3.3.2. You can see it on the demo: https://imperavi.com/redactor/examples/images-and-files/image-resizing-and-positioning/

1. Edit the image, position it center.
2. Resize the image by dragging the bottom right.

You can see that the image is immediately left aligned.

Seems to be the max-wdith applied to the figure that wraps the image (line 17110 in redactor.js). That'll always mean the contained element can't respect alignment because the figure isn't full width.
